name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: apt-get update
        run: sudo apt-get update -y

      - name: set up python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}
          cache-dependency-path: "pyproject.toml"

      - name: install invoke
        run: pip install invoke

      - name: build
        run: inv build

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
